### ISSUE TITLE
Pax-exam unit test fails when JDK 8 is used

### ISSUE THREAD

**Issue by cmoulliard** [gpe-mw-training/camel-labs#13]
Pax-exam unit test fails when JDK 8 is used (= Module 8 / osgi-camel-pax-testing)

**Comment by cmoulliard** [comment]
To be tested with solution branch and commit to be applied also to exercise branche.

**Comment by honghuac** [comment]
@cmoulliard 
I will close this issue, as I have one similar issue (https://github.com/redhat-gpe/fuse_integration/issues/67) that will address your findings. Thanks.
